<?php
/*
Version: 0.1.4 http://providelivehelp.com
Date: 11-JUN-2010
Copyright: (c) 2010 Provide Live Help
Created By: Sudhansu Ranjan Mangaraj (modulesoft.com)
*/
$webchat = Mage::getModel('websitechat/config');
?>
<div class="block base-mini alfasrch">
	<?php if($webchat->getWebsiteChat('title') !='' ): ?>
	<div class="block-title">
		<strong><span><?php echo $this->__($webchat->getWebsiteChat('title')); ?></span></strong>
	</div>
	<?php endif; ?>
	<div class="block-content" style="padding:10px 5px 10px 5px; text-align:center;">
		<?php echo $webchat->getWebsiteChat('chat_button_html'); ?>
	</div>
</div>
