<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Onsale
 * @version    2.4.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
    ?>
<?php if (strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE 7.0') !== false): ?>
<script language="JavaScript">
	window.onload = function()
	{
		var elems = document.getElementsByTagName('table')
		for(var i=0; i < elems.length; i++){
			if (elems[i].className == 'onsale-category-container'){
				elems[i].setAttribute('width', '99%');
				elems[i].setAttribute('width', '100%');
			}
		}
	};
</script>
<?php endif; ?>
