<?php
/**
 * MageWorx
 * Order Surcharge extension
 *
 * @category   MageWorx
 * @package    MageWorx_OrdersSurcharge
 * @copyright  Copyright (c) 2016 MageWorx (http://www.mageworx.com/)
 */
?>
<?php
$_source = $this->getSource();
$_order = $this->getOrder();
?>
<tr>
    <td <?php echo $this->getLabelProperties()?>>
        <div class="summary">
            <?php echo Mage::helper('mageworx_orderssurcharge')->__('Linked Amount') ?>
        </div>
    </td>
    <td <?php echo $this->getValueProperties()?>>
        <?php echo $this->displayAmount($_source->getLinkedAmount(), $_source->getBaseLinkedAmount()); ?>
    </td>
</tr>
