<?php
 /**
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2018 GoMage (https://www.gomage.com)
 * @author       GoMage
 * @license      https://www.gomage.com/license-agreement/  Single domain license
 * @terms of use https://www.gomage.com/terms-of-use
 * @version      Release: 5.9.4
 * @since        Class available since Release 4.1
 */ 
?>
<script type="text/javascript">
    //<![CDATA[
    payone = new PAYONE.Service.CreditCardCheck(
            new PAYONE.Handler.CreditCardCheck.LightCheckout()
    );

    Event.observe(window, 'load', function () {
        payone.form = payment.form;
        checkout.LightcheckoutSubmit = checkout.LightcheckoutSubmit.wrap(
                function (origMethod) {
                    payone.exec(origMethod);
                }
        );
    });
    //]]>
</script>