<?php
 /**
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2018 GoMage (https://www.gomage.com)
 * @author       GoMage
 * @license      https://www.gomage.com/license-agreement/  Single domain license
 * @terms of use https://www.gomage.com/terms-of-use
 * @version      Release: 5.9.4
 * @since        Class available since Release 1.0
 */ 
?>

<script type="text/javascript">
//<![CDATA[
LightCheckoutCalendar.Calendar._SDN = <?php echo $days['abbreviated']?>; // short day names
LightCheckoutCalendar.Calendar._SMN = <?php echo $months['abbreviated']?>; // short month names
//]]>
</script>
