<?php if (!($_shippingRateGroups = $this->getShippingRates())): ?>
    <strong><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></strong>
<?php else: ?>
<dl class="shipment-methods">
    <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
        <dt><?php echo $this->getCarrierName($code) ?></dt>
        <dd>
            <ul>
            <?php foreach ($_rates as $_rate): ?>
                <?php
                $shipMethodArray = explode('_', $_rate->getCode());
                if ($shipMethodArray[0] == 'upstablerates' && count($shipMethodArray) > 2) : ?>
                <li>
                   <?php if ($_rate->getErrorMessage()): ?>
                        <ul class="messages">
                            <li class="error-msg">
                                <ul>
                                    <li><?php echo $_rate->getErrorMessage() ?></li>
                                </ul>
                            </li>
                        </ul>
                        <?php else: ?>
                        <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>"
                               id="s_method_<?php echo $_rate->getCode() ?>"<?php if ($_rate->getCode() === $this->getAddressShippingMethod()) echo ' checked="checked"' ?>/>
                            <strong><label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $_rate->getMethodTitle() ?></strong>
                            <strong>
                                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                                <?php echo $_excl; ?>
                                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                <?php endif; ?>
                            </strong>
                        </label>
                        <?php endif ?>
                    <?php
                    $shipMethodArray = explode('_', $_rate->getCode());
                    if ($shipMethodArray[0] == 'upstablerates' && count($shipMethodArray) > 2) {
                        $upstablerates = Mage::getResourceModel('upstablerates_shipping/carrier_upstablerates')->loadPk($shipMethodArray[2]);
                        echo '<span style="display:block;font-weight:normal !important;margin-bottom:7px;" class="imUpslabelsInvMethodDescription">' . $upstablerates['method_description'] . '</span>';
                    }
                    ?>
                    <?php else: ?>
                    <?php if ($_rate->getErrorMessage()): ?>
                        <ul class="messages">
                            <li class="error-msg">
                                <ul>
                                    <li><?php echo $_rate->getErrorMessage() ?></li>
                                </ul>
                            </li>
                        </ul>
                        <?php else: ?>
                        <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>"
                               id="s_method_<?php echo $_rate->getCode() ?>"<?php if ($_rate->getCode() === $this->getAddressShippingMethod()) echo ' checked="checked"' ?>/>
                        <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $_rate->getMethodTitle() ?>
                            <strong>
                                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                                <?php echo $_excl; ?>
                                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                <?php endif; ?>
                            </strong>
                        </label>
                        <?php endif ?>
                    <?php endif ?>

                </li>
            <?php endforeach; ?>
            </ul>
			<?php if ($infoText = $this->getInfoText($code)) { ?>
			<div class="shipment-info">
				<?php echo $infoText ?>
			</div>
			<?php } ?>
        </dd>
    <?php endforeach; ?>
</dl>
<?php endif; ?>