<?php
/**
 * MageWorx
 * Order Surcharge extension
 *
 * @category   MageWorx
 * @package    MageWorx_OrdersSurcharge
 * @copyright  Copyright (c) 2016 MageWorx (http://www.mageworx.com/)
 */
?>
<?php
$_source = $this->getSource();
$_order = $this->getOrder();
?>
<tr>
    <td class="label">
        <div class="summary-collapse">
            <?php echo Mage::helper('mageworx_orderssurcharge')->__('Order Surcharge') ?>
        </div>
    </td>
    <td>
        <?php echo $this->displayAmount($_source->getSurchargeAmount(), $_source->getBaseSurchargeAmount()); ?>
    </td>
</tr>
