<?php
/**
 * AdvancedInvoiceLayout Pdf crosssell item template
 *
 * @section LICENSE
 * This file is created by vianetz <info@vianetz.com>.
 * The Magento module is distributed under a commercial license.
 * Any redistribution, copy or direct modification is explicitly not allowed.
 *
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@vianetz.com so we can send you a copy immediately.
 *
 * @category    Vianetz
 * @package     Vianetz\AdvancedInvoiceLayout
 * @author      Christoph Massmann, <C.Massmann@vianetz.com>
 * @link        http://www.vianetz.com
* @copyright   Copyright (c) 2006-18 vianetz - C. Massmann (http://www.vianetz.com)
 * @license     http://www.vianetz.com/license Commercial Software License
 */

/**
 * @var $this Vianetz_AdvancedInvoiceLayout_Block_Pdf_Item_Crosssell
 */
?>
<?php echo $this->__('You may also be interested in the following product(s):'); ?>
<table class="crosssellItem">
    <tr>
        <td class="image">
            <?php if ($this->isProductImagePath()): ?>
                <img src="<?php echo $this->getProductImagePath(); ?>" />
            <?php endif; ?>
        </td>
        <td>
            <strong><?php echo $this->getItem()->getName(); ?></strong><br />
            <?php echo $this->getProductShortDescription(); ?><br/>
            <span class="price"><?php echo $this->formatPrice($this->getItemPrice($this->getItem())); ?></span>
        </td>
    </tr>
</table>