<?php
/**
 * AdvancedInvoiceLayout Pdf shipment item template
 *
 * @section LICENSE
 * This file is created by vianetz <info@vianetz.com>.
 * The Magento module is distributed under a commercial license.
 * Any redistribution, copy or direct modification is explicitly not allowed.
 *
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@vianetz.com so we can send you a copy immediately.
 *
 * @category    Vianetz
 * @package     Vianetz\AdvancedInvoiceLayout
 * @author      Christoph Massmann, <C.Massmann@vianetz.com>
 * @link        http://www.vianetz.com
* @copyright   Copyright (c) 2006-18 vianetz - C. Massmann (http://www.vianetz.com)
 * @license     http://www.vianetz.com/license Commercial Software License
 */

/**
 * @var $this Vianetz_AdvancedInvoiceLayout_Block_Pdf_Item_Shipment
 */
?>

<tr>
    <td class="columnSku"><?php echo $this->formatWithLineBreak($this->getItem()->getSku()); ?></td>
    <td class="columnName">
        <?php echo $this->getItem()->getName(); ?><br />
        <span class="smallerFont">
            <?php if ($this->getProductShortDescription()): ?>
            <?php echo $this->getProductShortDescription(); ?><br/>
            <?php endif; ?>

            <?php if ($this->getItemOptions()): ?>
            <ul class="itemOptionList">
            <?php foreach ($this->getItemOptions() as $option): ?>
                <li><span class="itemOptionLabel"><?php echo $option['label']; ?>:</span> <?php echo $this->getOptionValue($option); ?></li>
            <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </span>
        <?php if ($this->isProductImagePath()): ?>
            <img class="image" src="<?php echo $this->getProductImagePath(); ?>" />
        <?php endif; ?>
    </td>
    <td class="columnQty"><?php echo $this->getItemQty($this->getItem()); ?></td>
</tr>

<?php if ($this->getBundleItems()): ?>
<?php foreach ($this->getBundleItems() as $bundleItem): ?>
    <tr>
        <td class="columnSku"><?php echo $this->formatWithLineBreak($bundleItem->getSku()); ?></td>
        <td class="columnName"><?php echo $bundleItem->getName(); ?></td>
        <td class="columnQty"><?php echo $this->getItemQty($bundleItem); ?></td>
    </tr>
<?php endforeach; ?>
<?php endif; ?>
