<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
<div class="main-login main-center">
	<form id="request_academic_account"
		class="infusion-form" 
		accept-charset="UTF-8" 
		action="https://tr300.infusionsoft.com/app/form/redirectProcess/278b6b0c3a00830d3a40e2ce4087dfae?referrer=https%3A%2F%2Fwww.repairzoom.com%2Fipad-repair%2Fschool-ipad-repair-college-university-education-accounts.html" 
		target="_top" referrer="https%3A%2F%2Fwww.repairzoom.com%2Fipad-repair%2Fschool-ipad-repair-college-university-education-accounts.html" 
		method="POST" 
		name="Lead Entry - School Leads" 
		onsubmit="
			var form = document.forms[0]; 
			var resolution = document.createElement('input'); 
			resolution.setAttribute('id', 'screenResolution'); 
			resolution.setAttribute('type', 'hidden'); 
			resolution.setAttribute('name', 'screenResolution'); 
			var resolutionString = screen.width + 'x' + screen.height; 
			resolution.setAttribute('value', resolutionString); 
			form.appendChild(resolution); 
			var pluginString = ''; 
			if (window.ActiveXObject) { 
				var activeXNames = {
					'AcroPDF.PDF':'Adobe Reader', 
					'ShockwaveFlash.ShockwaveFlash...ent('input'); plugins.setAttribute('id', 'pluginList'); plugins.setAttribute('type', 'hidden'); plugins.setAttribute('name', 'pluginList'); plugins.setAttribute('value', pluginString); form.appendChild(plugins); var java = navigator.javaEnabled(); var javaEnabled = document.createElement('input'); javaEnabled.setAttribute('id', 'javaEnabled'); javaEnabled.setAttribute('type', 'hidden'); javaEnabled.setAttribute('name', 'javaEnabled'); javaEnabled.setAttribute('value', java); form.appendChild(javaEnabled);"
		>
		<input id="timeZone" name="timeZone" value="UTC" type="hidden">
		<input name="inf_form_xid" value="278b6b0c3a00830d3a40e2ce4087dfae" type="hidden">
		<input name="inf_form_name" value="Lead Entry - School Leads" type="hidden">
		<input name="infusionsoft_version" value="1.66.0.58" type="hidden">
		<div class="form-group">
			<label for="inf_field_FirstName" class="cols-sm-2 control-label">First Name <span class="required">*</span></label>
			<div class="cols-sm-10">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
					<input type="text" class="form-control required-entry" name="inf_field_FirstName" id="inf_field_FirstName"  placeholder="Enter your First Name"/>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="inf_field_LastName" class="cols-sm-2 control-label">Last Name <span class="required">*</span></label>
			<div class="cols-sm-10">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
					<input type="text" class="form-control required-entry" name="inf_field_LastName" id="inf_field_LastName"  placeholder="Enter your Last Name"/>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="inf_field_Email" class="cols-sm-2 control-label">Email <span class="required">*</span></label>
			<div class="cols-sm-10">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
					<input type="text" class="form-control required-entry validate-email" name="inf_field_Email" id="inf_field_Email"  placeholder="Enter your Email"/>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="inf_field_Phone1" class="cols-sm-2 control-label">Phone <span class="required">*</span></label>
			<div class="cols-sm-10">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-phone" aria-hidden="true"></i></span>
					<input type="text" class="form-control required-entry validate-phoneLax" name="inf_field_Phone1" id="inf_field_Phone1"  placeholder="Enter your Phone"/>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="inf_field_Company" class="cols-sm-2 control-label">School or School District <span class="required">*</span></label>
			<div class="cols-sm-10">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-bookmark"></i></span>
					<input type="text" class="form-control required-entry" name="inf_field_Company" id="inf_field_Company"  placeholder="Enter your School or School District"/>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="inf_field_JobTitle" class="cols-sm-2 control-label">Position <span class="required">*</span></label>
			<div class="cols-sm-10">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-bookmark"></i></span>
					<input type="text" class="form-control required-entry" name="inf_field_JobTitle" id="inf_field_JobTitle"  placeholder="Enter your Position"/>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="inf_custom_ProductInterest0" class="cols-sm-2 control-label">Product Interest</label>
			<div class="cols-sm-10">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-bookmark"></i></span>
					<select class="selectpicker form-control" name="inf_custom_ProductInterest0" id="inf_custom_ProductInterest0">
					  	<option value="">Please select one</option>
					  	<option value="iPad Repair">iPad Repair</option>
					  	<option value="iPhone Repair">iPhone Repair</option>
					  	<option value="Mac Repair">Mac Repair</option>
					  	<option value="Other">Other</option>
					  	<option value="Multiple">Multiple</option>
					</select>
				</div>
			</div>
		</div>
		<div class="form-group ">
			<input type="submit" id="button" class="btn btn-primary btn-lg btn-block login-button" value="Submit">
		</div>
	</form>
</div>
<script type="text/javascript">
    //< ![CDATA[
        var customForm = new VarienForm('request_academic_account');
    //]]>
</script>