<?php
/**
 * Magpleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Magpleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   Magpleasure
 * @package    Magpleasure_Assignorder
 * @version    1.0.1
 * @copyright  Copyright (c) 2012 Magpleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>
<script type="text/javascript">
    var templatePattern =
        '<div class="assignorder-dialog">'+
            '<div class="assignorder-message">'+
                '<div class="order"><span><?php echo $this->__("Order: %s", "#{{increment_id}}"); ?></span></div>'+
                '<div class="arrow">&nbsp;</div>'+
                '<div class="customer"> <span class="name">{{customer_name}}</span><br/><span class="email">{{customer_email}}</span> </div>'+
                '<div class="fixed"></div>'+
            '</div>'+
            '<div class="assignorder-checkboxes" >'+
                '<form id="assignorder-form" action="<?php echo $this->getAssignUrl(); ?>" method="POST">'+
                    '<input type="hidden" class="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>">'+
                    '<input type="hidden" class="hidden" name="customer_id" value="{{customer_id}}">'+
                    '<div class="line">'+
                        '<input type="checkbox" class="checkbox" name="overwrite_name" id="overwrite_name_checkbox">'+
                        '<label for="overwrite_name_checkbox"><?php echo $this->__("Overwrite Guest Name"); ?></label>'+
                    '</div>'+
                    '<div class="line">'+
                        '<input type="checkbox" class="checkbox" name="send_email" id="send_email_checkbox"<?php if (!$this->_helper()->configNotificationEnabled()): ?> disabled<?php endif; ?>>'+
                        '<label for="send_email_checkbox"><?php echo $this->__("Notify Customer"); ?></label>'+
                    '</div>'+
                '</form>'+
            '</div>'+
        '</div>';

    var templateMessage = new Template(templatePattern, new RegExp('(^|.|\\r|\\n)({{\\s*(\\w+)\\s*}})', ""));

    var assignorderRowClick = function(){
        var tds = $$('#assignorderGrid tr.on-mouse td');
        var data = {
            'order_id': '<?php echo $this->getOrderId(); ?>',
            'increment_id': '<?php echo $this->getIncrementId(); ?>',
            'customer_name': tds[1].innerHTML.toString().trim(),
            'customer_email': tds[2].innerHTML.toString().trim(),
            'customer_id': tds[0].innerHTML.toString().trim(),
            'send_email': <?php echo $this->getConfSendEmail() ? 'true' : 'false'; ?>,
            'overwrite_name': <?php echo $this->getConfOverwriteName() ? 'true' : 'false'; ?>
        };
        var message = templateMessage.evaluate(data);
        Dialog.confirm(message,{
            className: "magento",
            id: "mp_assignorder_dialog",
            width: 390,
            height: 165,
            title: '<?php echo $this->__("Confirmation"); ?>',
            destroyOnClose: true,
            closable: true,
            draggable: true,
            okLabel: '<?php echo $this->__("Assign Order"); ?>',
            cancelLabel: '<?php echo $this->__("Cancel"); ?>',
            onShow: (function(event){
                $('send_email_checkbox').checked = data.send_email;
                $('overwrite_name_checkbox').checked = data.overwrite_name;
            }).bind(data),
            onOk: function(event){
                $('assignorder-form').submit();
            }
        });
    };
</script>