<div class="content-header">
    <h3 class="icon-head head-devtools-systemcheck"><?php echo $this->__('Report Inspector'); ?></h3>
</div>

<div class="entry-edit">
	<form action="<?php echo $this->getUrl('devtools/adminhtml_dev/tailFile'); ?>" method="post" id="log_inspector_form">

		<label><?php echo $this->__('File'); ?>
			<?php echo $this->getReportDropdown(); ?>
		</lablel>

		<label><?php echo $this->__('Search the returned data'); ?>
			<input class="input-text" type="text" name="grep" title="<?php echo $this->__('Search log file'); ?>" />
		</label>

		<label><?php echo $this->__('Show # lines'); ?>
			<input class="input-text" type="text" name="devtools_show" title="<?php echo $this->__('Qty of lines'); ?>" value="50"  />
		</label>

		<a href="" onclick="DevLog.refresh(); return false;"><?php echo $this->__('Refresh'); ?></a>
		<a href="" onclick="DevLog.purge('report'); return false;"><?php echo $this->__('Purge'); ?></a>

		<input style="display:none" type="submit" />
	</form>
	<div id="log-console" class="devconsole">&nbsp;</div>
</div>

<script type="text/javascript">
	var DevLog = new Devtools.Log('log_inspector_form', '<?php echo $this->getUrl('devtools/adminhtml_dev/tailFile'); ?>');
</script>