<div class="content-header">
    <h3 class="icon-head head-devtools-sqlqueries"><?php echo $this->__('SQL Queries'); ?></h3>
</div>

<div class="entry-edit">
    <form action="<?php echo $this->getUrl('devtools/adminhtml_dev/sql'); ?>" method="post" id="sql_form">
        <label><?php echo $this->__('Search the returned data'); ?>
            <input class="input-text" type="text" name="grep" title="<?php echo $this->__('Search log file'); ?>" />
        </label>

        <a href="" onclick="Sql.go(); return false;"><?php echo $this->__('Go'); ?></a>
    </form>
    <div id="log-console" class="devconsole">&nbsp;</div>
</div>

<script type="text/javascript">
    var Sql = new Devtools.Sql('sql_form');
</script>