<?php
/**
 * Mason Web Development
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2009 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
//get all Profiles 
$pressarticles = $this->getPressarticles();
?>
<script type="text/javascript" src="<? echo $this->getSkinUrl("js/modalbox/modalbox.js") ?>"></script>
<style>
#MB_overlay {
	position: absolute;
	margin: auto;
	top: 0;	left: 0;
	width: 100%; height: 100%;
	z-index: 9999;
	background-color: grey!important;
}
#MB_overlay[id] { position: fixed; }

#MB_window {
	position:absolute;
	top: 0;
	border: 0 solid;
	text-align:left;
	z-index:10000;
}
#MB_window[id] { position: fixed!important; }

#MB_frame {
	position:relative;
	background-color: #FFF;
	height:100%;
}

#MB_header {
	margin:0;
	height: 28px;
}

#MB_content {
	padding: 6px .75em;
	overflow:auto;
}

#MB_caption {
	font: bold 85% "Verdana", Arial, sans-serif;
	/*text-shadow: #FFF 0 1px 0;*/
	padding: .5em 2em 0 .75em;
	margin: 0;
	text-align: left;
}

#MB_close {
	display:block;
	position:absolute;
	right:5px; top:4px;
	padding:2px 3px;
	font-weight:bold;
	text-decoration:none;
	font-size:13px;
}
#MB_close:hover {
	background:transparent;
}

#MB_loading {
	padding: 1.5em;
	text-indent: -10000px;
	background: transparent url(spinner.gif) 50% 0 no-repeat;
}

/* Color scheme */
#MB_window {
	background-color: #000;
	color: grey;
}
#MB_content { border-top: 1px solid #F9F9F9; }
#MB_header {
  background-color: grey;
  border-bottom: 1px solid #CCC;
}
#MB_caption { color:#FFF }
#MB_close { color:#154C7C }
#MB_close:hover { color: grey }


/* Alert message */
.MB_alert {
	margin: 10px 0;
	text-align: center;
}
</style>

<h1>Press coverage</h1>
<div style="float: left; width: 400px; border: 0px solid black;">
<?php foreach($pressarticles as $n): ?>
	<?php if ($n->getData("is_active")):?>
		<?php if($n->getData("picture")):?>
			<?php $pressarticlesUrl = $this->getUrl('*/*/read', array("id" => $n->getData("profile_id"))); ?>
		<?php endif; ?>
		<div class="ColumnLeft" style="float: left; border-bottom: 1px solid #ddd; padding-bottom: 10px; padding-top: 10px; width: 350px; border: 0px solid red;">
			<table style="table-layout:fixed;">
			<tr valign="top">
			<td style="overflow:hidden;" width="100px">
				<?php if($n->getData("thumbnail")):?>
					<div id="<?php echo $n->getData("profile_id"); ?>" style="float: left; height: 90px; width: 90px; background-repeat:no-repeat; background-image: url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . "media/" . $n->getData("thumbnail") ?>');" />
				<?php endif; ?>
			</td>
			<td style="padding-left: 10px">
				<a href="<? echo $pressarticlesUrl ?>" title="<?php echo $n->getData("content_heading"); ?>" onclick="Modalbox.show(this.href, {title: this.title, transitions: false,  width: 700, height: 600}); return false;">
					<h2><?php echo $this->formatDate($n->getData("creation_time")); ?> - <?php echo $n->getData("content_heading"); ?></h2>
				</a>
				<p><?php echo $n->getContent(); ?></p>
			</td>
			</tr>
			</table>
		</div>
	<?php endif; ?>
<?php endforeach; ?>
</div>




