<?php

/*

Creare Sitemap - gets CMS Pages - TLC's and SC's - and 10 best products per category

*/

function getCreareCMSPages(){
	
	$cms = Mage::getModel('cms/page')->getCollection();
	$html = "";
	foreach($cms as $cmspage):
		$page = $cmspage->getData();	
		if($page['identifier'] == "no-route" || $page['identifier'] == "enable-cookies" || $page['identifier'] == "empty" || $page['identifier'] == "sitemap2"){ /* do nothing or something here */ } else {
			if($page['identifier'] == "home"){
				$html .= "<li><a href=\"/\" title=\"".$page['title']."\">".$page['title']."</a></li>\n"; // this is for a nice local link to home
			} else {
				$html .= "<li><a href=\"".Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$page['identifier']."\" title=\"".$page['title']."\">".$page['title']."</a></li>\n";
			}
		}
	endforeach;
	
	
	return $html;	
}


?>
<style type="text/css">
.smh2, .strongsm { display: block; }
.siteul { margin: 5px; padding: 0 0 0 10px; }
.siteul li { list-style:inside; font-size:1em!important; }
.sitecatul { margin: 0 5px; padding: 0 0 0 10px; }
.sitecatul li { list-style:none; font-size:1em!important; }
.sitecatul li ul { margin: 0 5px; padding: 0 0 0 10px; }
.sitecatul li ul li { list-style:inside; }
.two-column { width: 50%; float: left; display: block; }
</style>
<div class="two-column">
<h2 class="smh2">Our Main Pages</h2>
    <ul class="siteul">
        <?php echo getCreareCMSPages(); // prints out our cms pages ?>
        <li><a href="/sitemap.xml" title="XML Sitemap">XML Sitemap</a></li>
    </ul>
</div>
<div class="two-column">
<h2 class="smh2">Our Categories</h2>
<?php // Thanks to Luci @ Creare for the following code ?>
<?php $_helper = Mage::helper('catalog/category') ?>
<?php $_categories = $_helper->getStoreCategories() ?>
<?php if (count($_categories) > 0): ?>
	<ul class="sitecatul">
		<?php foreach($_categories as $_category): ?>

			<li>
				<strong class="strongsm"><a href="<?php echo Mage::getModel('catalog/category')->load($_category->getId())->getUrl(); ?>" title="<?php echo $_category->getName() ?>">
									<?php echo $_category->getName() ?>
								</a></strong>
				<?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
				<?php $_subcategories = $_category->getChildrenCategories() ?>
				<?php if (count($_subcategories) > 0): ?>
					<ul>
						<?php foreach($_subcategories as $_subcategory): ?>
							<?php $_nextcategory = Mage::getModel('catalog/category')->load($_subcategory->getId()) ?>
                            <?php $_nextsubcategories = $_nextcategory->getChildrenCategories() ?>
							<li>
								<a href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>" title="<?php echo $_subcategory->getName() ?>">
									<?php echo $_subcategory->getName() ?>
								</a>
                                <?php if (count($_nextsubcategories) > 0): ?>
                                <ul>
                                	<?php foreach($_nextsubcategories as $_nextsubcat): ?>
                                    	<li>
                                        	<a href="<?php echo $_helper->getCategoryUrl($_nextsubcat) ?>" title="<?php echo $_subcategory->getName() ?> - <?php echo $_nextsubcat->getName() ?>">
												<?php echo $_nextsubcat->getName() ?>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                                <?php endif; ?>
							</li>
						<?php endforeach; ?>
					</ul>
				<?php endif; ?>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>
</div>