<?php /** @var Mage_Catalog_Block_Product_List $this */
$pc = $this->getLoadedProductCollection(); /** @var Mage_Catalog_Model_Resource_Product_Collection $pc */
$hOutput = $this->helper('catalog/output'); /** @var Mage_Catalog_Helper_Output $hOutput */
$hImage = $this->helper('catalog/image'); /** @var Mage_Catalog_Helper_Image $hImage */
/**
 * 2019-12-01 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
 * @param string $k
 * @param mixed|null $d [optional]
 * @return mixed
 */
$cfg = function($k) {return Mage::getStoreConfig(false !== strpos($k, '/') ? $k : "porto_settings/category/$k");};
$aspect_ratio = true;
$ratio_width = $this['image_width'];
if (!$ratio_width) {
	$ratio_width = $cfg('ratio_width');
}
$ratio_height = $this['image_height'];
if (!$ratio_height) {
	$ratio_height = $cfg('ratio_height');
}
$ratio_width = $ratio_width ?: 300;
$ratio_height = $ratio_height ?: 400;
if (!$pc->count()) { ?>
	<div class='category-products'>
		<p class='note-msg'><?= $this->__('There are no products matching the selection.') ?></p>
	</div>
<?php } else { ?>
	<div class='category-products'>
		<?= $this->getToolbarHtml() ?>
		<ul class='products-grid columns4 hide-addtolinks'>
		<?php foreach ($pc as $p) {?>
			<li class='item'>
				<div class='item-area'>
					<div class='product-image-area'>
						<div class='loader-container'>
							<div class='loader'>
								<i class='ajax-loader medium animate-spin'></i>
							</div>
						</div>
						<?php
							$base_url = $this->getUrl();
							if (strpos($base_url,'?') !== false) {
								$base_url = explode('?', $this->getUrl());
							}
							if (is_array($base_url)) {
								$base_url = $base_url[0];
							}
							$base_url .= 'quickview/index/view/';
							$quickview_url = $base_url.'id/'.$p->getId();
						?>
						<a href='<?= $quickview_url; ?>' class='quickview-icon'
						><i class='icon-export'></i><span><?= $this->__('Quick View'); ?></span></a>
						<a 
							class='product-image'
							href='<?= $p->getProductUrl() ?>' 
							title="<?= $this->stripTags($this->getImageLabel($p, 'small_image'), null, true) ?>" 
						>
							<img
								alt="<?= $this->stripTags($this->getImageLabel($p, 'small_image'), null, true) ?>"
								class="defaultImage"
								id="product-collection-image-<?= $p->getId(); ?>"
								src="<?= $hImage->init($p, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?>"
								width="<?= $ratio_width; ?>"
							/>
							<img
								alt="<?= $this->stripTags($this->getImageLabel($p, 'thumbnail'), null, true) ?>"
								class="hoverImage"
								src="<?= $hImage->init($p, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?>"
								width="<?= $ratio_width; ?>"
							/>
							<?php
								$sale_label = false;
								$specialprice = $p->getFinalPrice();
								$orgprice = $p->getPrice();
								$now = date("Y-m-d");
								$specialPriceFromDate = substr($p->getSpecialFromDate(),0,10);
								$specialPriceToDate = substr($p->getSpecialToDate(),0,10);
								if ($specialprice < $orgprice) {
									if ($specialPriceToDate != '' || $specialPriceFromDate != '') {
										if (
											(
												$specialPriceToDate != ''
												&& $specialPriceFromDate != ''
												&& $now >= $specialPriceFromDate
												&& $now<=$specialPriceToDate
											)
											|| ($specialPriceToDate == '' && $now >=$specialPriceFromDate)
											|| ($specialPriceFromDate == '' && $now<=$specialPriceToDate)
										) {
											$sale_label = true;
											?>
												<div class="product-label" style="right: 10px;">
													<span class="sale-product-icon">
														<?= $cfg("porto_settings/product_label/sale_label_text") ?>
													</span>
												</div>
											<?php
										}
									}
								}
								$now = date("Y-m-d");
								$newsFrom = substr($p->getData('news_from_date'),0,10);
								$newsTo = substr($p->getData('news_to_date'),0,10);
								if ($newsTo != '' || $newsFrom != '') {
									if (
										($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo)
										|| ($newsTo == '' && $now >=$newsFrom)
										|| ($newsFrom == '' && $now<=$newsTo)
									) {
										?>
										<div class="product-label" style="right: 10px; <?= ($sale_label)?"top: 40px;":""; ?>">
											<span class="new-product-icon">
												<?= $cfg("porto_settings/product_label/new_label_text");?>
											</span>
										</div>
										<?php
									}
								}
							?>
						</a>
					</div>
					<div class='details-area'>
	<!-- 2019-12-01 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
	"Disable the Mage_Review and Mage_Rating modules": https://github.com/repairzoom/m1/issues/43 -->
						<h2 class='product-name'>
							<a href="<?= $p->getProductUrl() ?>" title="<?= $this->stripTags($p->getName(), null, true) ?>"
							><?= $hOutput->productAttribute($p, $p->getName(), 'name') ?></a>
						</h2>
						<?php
							if ($this->getChild('name.after')) {
								$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
								foreach ($_nameAfterChildren as $_nameAfterChildName) {
									$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);	$_nameAfterChild->setProduct($p);
									echo $_nameAfterChild->toHtml();
								}
							}
							echo $this->getPriceHtml($p, true);
						?>
						<div class='actions'>
							<?php if (!$p->isSaleable()) { ?>
								<a
									href='javascript:void(0);'
									class='addtocart outofstock'
									title="<?= $this->__('Out of stock') ?>"
								><?= $this->__('Out of stock') ?></span></a>
							<?php } else { ?>
								<?php if (!($p->getTypeInstance(true)->hasOptions($p) || $p->isGrouped())) {  ?>
									<a
										class='addtocart'
										href='javascript:void(0)'
										onclick="setLocationAjax(this,'<?= $this->getAddToCartUrl($p) ?>','<?= $p->getId(); ?>')"
										title="<?= $this->__('Add to Cart') ?>"
									><i class='icon-cart'></i><span>&nbsp;<?= $this->__('Add to Cart') ?></span></a>
								<?php } else { ?>
									<a
										class='addtocart'
										href="javascript:showOptions('<?= $p->getId()?>')"
										title="<?= $this->__('Add to Cart') ?>"
									><i class='icon-cart'></i><span>&nbsp;<?= $this->__('Add to Cart') ?></span></a>
									<a
										class='fancybox'
										href='<?= $this->getUrl('ajaxcart/index/options',['product_id'=>$p->getId()]);?>'
										id='fancybox<?= $p->getId()?>'
										style='display:none'
									>Options</a>
								<?php } ?>
							<?php } ?>
							<div class="clearer"></div>
						</div>
					</div>
				</div>
				</li>
			<?php } ?>
		</ul>
		<script type='text/javascript'>
			var $j = jQuery;
			var $g = $j('.col-main .products-grid');
			var i;
			var nth = 'nth-child';
			for (i = 2; i < 9; i++) {
				$j(`li:${nth}(${i}n)`, $g).addClass(`${nth}-${i}n`);
				$j(`li:${nth}(${i}n+1)`, $g).addClass(`${nth}-${i}np1`);
			}
		</script>
		<div class='toolbar-bottom'>
			<?= $this->getToolbarHtml() ?>
		</div>
	</div>
<?php } ?>
<div class="swatches-js">
	<?php
	// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
	if ($this->getChild('after')) {
		$_afterChildren = $this->getChild('after')->getSortedChildren();
		foreach ($_afterChildren as $_afterChildName) {
			$_afterChild = $this->getChild('after')->getChild($_afterChildName);
			//set product collection on after blocks
			$_afterChild->setProductCollection($pc);
			echo $_afterChild->toHtml();
		}
	}
	?>
</div>