<?php /** @var Mage_Catalog_Block_Product_List $this */
$pc = $this->getLoadedProductCollection(); /** @var Mage_Catalog_Model_Resource_Product_Collection $pc */
$hOutput = $this->helper('catalog/output');
$_image_helper = $this->helper('catalog/image');
/**
 * 2019-12-01 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
 * @param string $k
 * @param mixed|null $d [optional]
 * @return mixed
 */
$cfg = function($k) {return Mage::getStoreConfig(false !== strpos($k, '/') ? $k : "porto_settings/category/$k");};
$aspect_ratio = $this['aspect_ratio'] ?: $cfg('aspect_ratio');
$ratio_width = $this['image_width'];
if (!$ratio_width) {
	$ratio_width = $cfg('ratio_width');
}
$ratio_height = $this['image_height'];
if (!$ratio_height) {
	$ratio_height = $cfg('ratio_height');
}
$ratio_width = $ratio_width ?: 300;
$ratio_height = $ratio_height ?: 400;
if (!$pc->count()) { ?>
	<div class='category-products'>
		<p class='note-msg'><?= $this->__('There are no products matching the selection.') ?></p>
	</div>
<?php } else { ?>
	<div class='category-products'>
		<?= $this->getToolbarHtml() ?>
		<?php $_columnCount = $cfg('porto_settings/category_grid/columns'); ?>
		<ul class='products-grid <?php if ($cfg('porto_settings/category_grid/flex_grid')):?>flex-grid<?php endif; ?> columns<?= $_columnCount; ?><?php if (!$cfg('porto_settings/category_grid/show_addtolinks')):?> hide-addtolinks<?php endif; ?><?php if (!$cfg('porto_settings/category_grid/show_addtocart')):?> hide-addtocart<?php endif; ?><?php if ($cfg('porto_settings/category_grid/move_actions')):?> move-action<?php endif; ?>'>
		<?php foreach ($pc as $_product) { ?>
		<?php $product = $_product; ?>
				<li class='item'><div class='item-area'>
				<div class='product-image-area'>
						<div class='loader-container'>
							<div class='loader'>
								<i class='ajax-loader medium animate-spin'></i>
							</div>
						</div>
						<?php
						if ( $cfg('quickview/general/enableview') ) {
							$base_url = $this->getUrl();
							if (strpos($base_url,'?')!==false)
								$base_url = explode('?',$this->getUrl());
							if (is_array($base_url))
								$base_url = $base_url[0];
							$base_url .= 'quickview/index/view/';
							$quickview_url = $base_url.'id/'.$_product->getId();
							?>
							<a href='<?= $quickview_url; ?>' class='quickview-icon'><i class='icon-export'></i><span><?= $this->__('Quick View'); ?></span></a>
						<?php
						}
						?>
						<a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
						<?php
							if ($cfg("alternative_image")) {
						?>
							<img id="product-collection-image-<?= $_product->getId(); ?>" class="defaultImage" src="<?php if ($aspect_ratio):?><?= $_image_helper->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?= $_image_helper->init($_product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" width="<?= $ratio_width; ?>" <?php if (!$aspect_ratio):?>height="<?= $ratio_height; ?>"<?php endif; ?> alt="<?= $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
							<img class="hoverImage" src="<?php if ($aspect_ratio):?><?= $_image_helper->init($_product, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?= $_image_helper->init($_product, 'thumbnail')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" width="<?= $ratio_width; ?>" <?php if (!$aspect_ratio):?>height="<?= $ratio_height; ?>"<?php endif; ?> alt="<?= $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>"/>
						<?php
							} else {
						?>
							<img id="product-collection-image-<?= $_product->getId(); ?>" src="<?php if ($aspect_ratio):?><?= $_image_helper->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?= $_image_helper->init($_product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" width="<?= $ratio_width; ?>" <?php if (!$aspect_ratio):?>height="<?= $ratio_height; ?>"<?php endif; ?> alt="<?= $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
						<?php
							}
						?>
						<?php
							$sale_label = false;
							// Get the Special Price
							$specialprice = $product->getFinalPrice();
							$orgprice = $product->getPrice();
							// Get the Special Price FROM date
							$now = date("Y-m-d");
							$specialPriceFromDate = substr($product->getSpecialFromDate(),0,10);
							// Get the Special Price TO date
							$specialPriceToDate = substr($product->getSpecialToDate(),0,10);
							// Get Current date
							$today =  time();

							if ($specialprice<$orgprice) {
								$save_percent = 100-round(($specialprice/$orgprice)*100);
								if ($specialPriceToDate != '' || $specialPriceFromDate != '') {
								if (($specialPriceToDate != '' && $specialPriceFromDate != '' && $now>=$specialPriceFromDate && $now<=$specialPriceToDate) || ($specialPriceToDate == '' && $now >=$specialPriceFromDate) || ($specialPriceFromDate == '' && $now<=$specialPriceToDate)) {
									if ($cfg("porto_settings/product_label/sale")) {
										$sale_label = true;
						?>
									<div class="product-label" style="right: 10px;"><span class="sale-product-icon"><?php if ($cfg("porto_settings/product_label/sale_label_type")):?><?= "-".$save_percent."%"; ?><?php else: ?><?= $cfg("porto_settings/product_label/sale_label_text");?><?php endif; ?></span></div>
						<?php
									}
								}
							}
							}
						?>
						<?php
							$now = date("Y-m-d");
							$newsFrom= substr($_product->getData('news_from_date'),0,10);
							$newsTo=  substr($_product->getData('news_to_date'),0,10);
							if ($newsTo != '' || $newsFrom != '') {
								if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo))
								{
									if ($cfg("porto_settings/product_label/new")) {
							?>
									<div class="product-label" style="right: 10px; <?= ($sale_label)?"top: 40px;":""; ?>"><span class="new-product-icon"><?= $cfg("porto_settings/product_label/new_label_text");?></span></div>
							<?php
									}
								}
							}
						?>
					</div>
					<div class="details-area">
						<?php if (!$cfg("porto_settings/category_grid/move_title")):?>
							<h2 class="product-name"><a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>"><?= $hOutput->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
						<?php endif;?>
	<!-- 2019-12-01 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
	"Disable the Mage_Review and Mage_Rating modules": https://github.com/repairzoom/m1/issues/43 -->
						<?php if ($cfg("porto_settings/category_grid/move_title")):?>
							<h2 class="product-name"><a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>"><?= $hOutput->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
						<?php endif;?>
						<?php
							if ($this->getChild('name.after')) {
								$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
								foreach ($_nameAfterChildren as $_nameAfterChildName) {
									$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);	$_nameAfterChild->setProduct($_product);
									echo $_nameAfterChild->toHtml();
								}
							}
						?>
						<?php if ($cfg("product_price")):?>
						<?= $this->getPriceHtml($_product, true) ?>
						<?php endif; ?>
						<?php if ($cfg("actions")):?>
						<div class="actions">
							<?php if ($cfg("qty_field")):?>
								<?php if ($product->isSaleable()): ?>
									<?php  if ( !($product->getTypeInstance(true)->hasOptions($product) || $product->isGrouped()) ) :  ?>
									<?php if (!$cfg("ajaxcart/addtocart/enablecategory")):?>
									<form id="addtocart_form_<?= $_product->getId(); ?>" action="<?= $this->getAddToCartUrl($_product) ?>" method="post">
										<input type="hidden" name="form_key" value="<?= Mage::getSingleton('core/session')->getFormKey(); ?>" />
									<?php endif; ?>
									<div class="qty-field">
										<label for="qty"><?= $this->__('Qty:') ?></label>
										<div class="qty-holder">
											<input type="text" name="qty" id="qty_<?= $_product->getId(); ?>" maxlength="12" value="<?= $product->getProductDefaultQty() * 1 ?>" title="<?= $this->__('Qty') ?>" class="input-text qty" />
											<div class="qty-changer">
												<a href="javascript:void(0)" class="qty_inc"><i class="icon-up-dir"></i></a>
												<a href="javascript:void(0)" class="qty_dec"><i class="icon-down-dir"></i></a>
											</div>
								</div>
							</div>
						<?php if (!$cfg("ajaxcart/addtocart/enablecategory")):?>
									</form>
									<?php endif; ?>
									<?php endif; ?>
								<?php endif; ?>
							<?php endif; ?>
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
							<a href="<?php if ($cfg("ajaxcart/addtolinks/enablecategory")):?>javascript:void(0)<?php else: ?><?= $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" <?php if ($cfg("ajaxcart/addtolinks/enablecategory")):?>onclick="ajaxWishlist(this,'<?= $this->helper('wishlist')->getAddUrl($_product) ?>','<?= $_product->getId()?>');"<?php endif;?> class="addtowishlist" title="<?= $this->__('Add to Wishlist') ?>"><i class="icon-wishlist"></i></a>
							<?php endif; ?>
							<?php if ($product->isSaleable()): ?>
								<?php  if ( !($product->getTypeInstance(true)->hasOptions($product)/*$_product->getData('has_options')*/ || $product->isGrouped()) ) :  ?>
									<a href="<?php if (!$cfg("ajaxcart/addtocart/enablecategory") && !$cfg("qty_field")): ?><?= $this->getAddToCartUrl($_product) ?><?php else: ?>javascript:void(0)<?php endif; ?>" class="addtocart" title="<?= $this->__('Add to Cart') ?>" <?php if ($cfg("ajaxcart/addtocart/enablecategory")):?>onclick="setLocationAjax(this,'<?= $this->getAddToCartUrl($_product) ?>','<?= $_product->getId(); ?>')"<?php elseif ($cfg("qty_field")): ?>onclick="document.getElementById('addtocart_form_<?= $_product->getId(); ?>').submit()"<?php endif; ?>><i class="icon-cart"></i><span>&nbsp;<?= $this->__('Add to Cart') ?></span></a>
								<?php else : ?>
									<a href="<?php if ($cfg("ajaxcart/addtocart/enablecategory")):?>javascript:showOptions('<?= $_product->getId()?>')<?php else: ?><?= $this->getAddToCartUrl($_product) ?><?php endif; ?>" class="addtocart" title="<?= $this->__('Add to Cart') ?>"><i class="icon-cart"></i><span>&nbsp;<?= $this->__('Add to Cart') ?></span></a>
									<a href='<?= $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?= $_product->getId()?>' style='display:none'>Options</a>
								<?php endif;?>
							<?php else: ?>
								<a href="javascript:void(0);" class="addtocart outofstock" title="<?= $this->__('Out of stock') ?>"><?= $this->__('Out of stock') ?></span></a>
							<?php endif; ?>
							<?php if ($cfg("compare") && $_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<a href="<?php if ($cfg("ajaxcart/addtolinks/enablecategory")):?>javascript:void(0)<?php else: ?><?= $_compareUrl ?><?php endif; ?>" <?php if ($cfg("ajaxcart/addtolinks/enablecategory")):?>onclick="ajaxCompare(this,'<?= $_compareUrl ?>','<?= $_product->getId()?>');"<?php endif; ?> class="comparelink" title="<?= $this->__('Add to Compare') ?>"><i class="icon-compare"></i></a>
							<?php endif; ?>
							<div class="clearer"></div>
						</div>
						<?php endif; ?>
					</div>
				</div></li>
			<?php } ?>
			</ul>
		<script type='text/javascript'>
			var $ = jQuery;
			var $g = $('.col-main .products-grid');
			var i;
			var nth = 'nth-child';
			for (i = 2, i < 9; i++) {
				$(`li:${nth}(${i}n)`, $g).addClass(`${nth}-${i}n`);
				$(`li:${nth}(${i}n+1)`, $g).addClass(`${nth}-${i}np1`);
			}
		</script>
		<div class='toolbar-bottom'>
			<?= $this->getToolbarHtml() ?>
		</div>
	</div>
<?php } ?>
<div class="swatches-js">
	<?php
	// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
	if ($this->getChild('after')) {
		$_afterChildren = $this->getChild('after')->getSortedChildren();
		foreach ($_afterChildren as $_afterChildName) {
			$_afterChild = $this->getChild('after')->getChild($_afterChildName);
			//set product collection on after blocks
			$_afterChild->setProductCollection($pc);
			echo $_afterChild->toHtml();
		}
	}
	?>
</div>