<?php
	//   image dimensions: style="width:1450px; height:500px;"
	$bannerCollection = Mage::getModel('bannerslider/bannerslider')->getCollection();
	$configData = Mage::getStoreConfig('bannerslider');
	$i = 0;
?>
<div id="banner-slider-demo-14" class="owl-carousel owl-theme owl-middle-narrow owl-banner-carousel">
	<?php
	$i = 0;
	foreach ($bannerCollection as $banner):
		$i++;
	?>
		<div class="item" style="background:url({{media url="wysiwyg/porto/homepage/slider/back.jpg"}}) center center no-repeat;background-size:cover;">
		    <div class="container" style="position:relative">
		      	<a href="<?php echo $banner['weblink'];?>">
					<img title="<?php echo $banner['title']?>" alt="<?php echo $banner['title']?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename']?>"/>				
					<?php if ($configData['settings']['show_description'] == '1'):?>
					<div class="banner_content"><p><?php echo $banner['content']; ?></p></div>
					<?php endif;?>
				</a>
		    </div>
		</div>
	<?php
	endforeach;
	?>
</div>
<script type="text/javascript">
  jQuery(function($){
    $("#banner-slider-demo-14").owlCarousel({
      autoPlay:true,
      lazyLoad:true,
      stopOnHover:true,
      pagination:false,
      autoPlay:true,
      navigation:true,
      navigationText:["<i class='icon-chevron-left'></i>","<i class='icon-chevron-right'></i>"],
      slideSpeed:500,
      paginationSpeed:100,
      singleItem:true,
      addClassActive:true,
      transitionStyle:"fade",
      afterMove:function(){
        $("#banner-slider-demo-5 .owl-item.active .content").each(function(){
          $(this).addClass($(this).attr("data-animation"));
        });
      },
      beforeMove:function(){
        $("#banner-slider-demo-5 .owl-item .content").each(function(){
          $(this).removeClass($(this).attr("data-animation"));
        });
      }
    });
  });
</script>

<?php /*

<script type="text/javascript" src="<?php echo $this->getSkinUrl('banner/ajaxtabs.js') ?>"></script>
<?php
	$bannerCollection = Mage::getModel('bannerslider/bannerslider')->getCollection();
	$configData = Mage::getStoreConfig('bannerslider');
	$i = 0;
?>
<div class="slide-container">
	<div class="slide-show" id="slide-images">		
		<div id="pettabs" class="indentmenu" style="display:none;">
			<ul>
		<?php
			foreach($bannerCollection as $banner):
				$i++;
		?>
				<li><a href="#" rel="tab<?php echo $i;?>" <?php if ($i == 1) { echo 'class="selected"'; }?>><?php echo $i;?></a></li>
		<?php
			endforeach;
		?>
			</ul>
		</div>
		<div style="width:960px;"> 
			<?php
			$i = 0;
			foreach ($bannerCollection as $banner):
				$i++;
			?>
			<div id="tab<?php echo $i;?>" class="tabcontent">				
				<a href="<?php echo $banner['weblink'];?>">
				<img title="<?php echo $banner['title']?>" alt="<?php echo $banner['title']?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename']?>"  style="width:960px; height:354px;"/>				
				<?php if ($configData['settings']['show_description'] == '1'):?>
				<div class="banner_content"><p><?php echo $banner['content']; ?></p></div>
				<?php endif;?>
				</a>				
			</div>
			<?php
			endforeach;
			?>								
		</div>
	</div>
</div>
<?php	
	$timeDelay = $configData['settings']['time_delay'] * 1000;
?>
<script type="text/javascript">
	<?php
		echo 'var delay = ' . $timeDelay . ';';
	?>
	var mypets=new ddtabcontent("pettabs");
	mypets.setpersist(true);
	mypets.setselectedClassTarget("link");
	mypets.init(delay);
</script>
*/?>